import type React from "react";
import type { Metadata } from "next";
import {
  Geist,
  Azeret_Mono as Geist_Mono,
  Dancing_Script,
  Caveat,
  Poppins,
} from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const dancingScript = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing-script",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Agregando Caveat
const caveat = Caveat({
  subsets: ["latin"],
  variable: "--font-caveat",
});

// Agregando Poppins
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Pagina Boiero",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dancingScript.variable} ${caveat.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
